apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ordersagademo.labels" . | nindent 4 }}
spec:
  selector:
    app: inventory-service
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
