apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ordersagademo
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ordersagademo/payment-service:0.1.0
          envFrom:
            - configMapRef:
                name: payment-service-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
