apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ordersagademo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        {{- include "ordersagademo.labels" . | nindent 8 }}
    spec:
      containers:
        - name: payment-service
          image: "{{ .Values.image.repository }}/payment-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: payment-service-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
