apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ordersagademo
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: ordersagademo/inventory-service:0.1.0
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: inventory-service-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
