apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ordersagademo
spec:
  selector:
    app: inventory-service
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
