apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ordersagademo
data:
  HTTP_ADDR: ":8080"
  KAFKA_BROKERS: "kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
  INVENTORY_GRPC_ADDR: "inventory-service:9090"
  KAFKA_CONSUMER_GROUP: "order-service"
